// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnhblsffdgrzzfuneroa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxuaGJsc2ZmZGdyenpmdW5lcm9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1ODc2ODAsImV4cCI6MjA3MzE2MzY4MH0.N4uOsJFjHZrVll0KPZfOoOvt500oR4SPL_WsSI874Zs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});